DELETE FROM `movie_record`
WHERE `movie_name` IN (
    'Jupiter Ascending',
    'Super 30',
    'Ludo',
    'Sherni',
    'Deadpool - 1',
    'The ledge',
    'Ant-Man 2023',
    'Gasslight',
    'Ghosted',
    'Sanak',
    'Scream VI',
    'Chor Nikal ke bhaga',
    'Dhamaka',
    'I spit on your grave',
    'The Hills have eyes - 1',
    'The Hills have eyes - 2',
    'Collar Bomb',
    'Faraaz',
    'NoEscape',
    'Mom',
    'Logan',
    'Reinfield',
    'The Popes Exorcist',
    'The Voyeurs'
);
